#! /bin/sh
xsetroot -cursor_name left_ptr &

pgrep -x polybar > /dev/null || polybar &

pgrep -x xautolock > /dev/null || xautolock -detectsleep -time 10 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'BetterLockScreen' 'Se bloqueara la pantalla en 30 segundos'" &

setxkbmap us


# set your wallpaper
# feh --bg-fill ~/Fondos/wallhaven-1p75xv_1920x1080.png.jpg

pgrep -x picom > /dev/null || picom &

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x nm-applet > /dev/null || nm-applet &

bspc monitor -d 1 2 3 4 5

bspc config focus_follows_pointer true
bspc config top_padding         32
bspc config border_width         1
bspc config window_gap           0


bspc config normal_border_color "#414868"
bspc config focused_border_color "#a9b1d6"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


